<?php

namespace RTB;

class Campaigns
{
    public static function getAll(): array
    {
        return [
            [
                "campaignname" => "Test_Banner_13th-31st_march_Developer",
                "advertiser" => "TestGP",
                "code" => "118965F12BE33FB7E",
                "appid" => "20240313103027",
                "tld" => "https=>//adplaytechnology.com/",
                "portalname" => "",
                "creative_type" => "1",
                "creative_id" => 167629,
                "day_capping" => 0,
                "dimension" => "320x480",
                "attribute" => "rich-media",
                "url" => "https=>//adplaytechnology.com/",
                "billing_id" => "123456789",
                "price" => 0.1,
                "bidtype" => "CPM",
                "image_url" => "https=>//s3-ap-southeast-1.amazonaws.com/elasticbeanstalk-ap-southeast-15410920200615/CampaignFile/20240117030213/D300x250/e63324c6f222208f1dc66d3e2daaaf06.png",
                "htmltag" => "",
                "from_hour" => "0",
                "to_hour" => "23",
                "hs_os" => "Android,iOS,Desktop",
                "operator" => "Banglalink,GrameenPhone,Robi,Teletalk,Airtel,Wi-Fi",
                "device_make" => "No Filter",
                "country" => "BGD",
                "city" => "",
                "lat" => "",
                "lng" => "",
                "app_name" => null,
                "user_list_id" => "0",
                "adplay_logo" => 1,
                "vast_video_duration" => null,
                "logo_placement" => 1,
                "hs_model" => null,
                "is_rewarded_inventory" => 0,
                "pixel_tag" => null,
                "dmp_campaign_audience" => 0,
                "platform" => null,
                "open_publisher" => 1,
                "audience_targeting" => 0,
                "native_title" => null,
                "native_type" => null,
                "native_data_value" => null,
                "native_data_cta" => null,
                "native_data_rating" => null,
                "native_data_price" => null,
                "native_img_icon" => null
            ],
            [
                "campaignname" => "Test_Banner_April_Developer",
                "advertiser" => "AdPlayTech",
                "code" => "120837A34BZ90DFT6",
                "appid" => "20240402093045",
                "tld" => "https=>//example.com/",
                "portalname" => "",
                "creative_type" => "2",
                "creative_id" => 192738,
                "day_capping" => 10,
                "dimension" => "728x90",
                "attribute" => "video",
                "url" => "https=>//example.com/",
                "billing_id" => "987654321",
                "price" => 0.2,
                "bidtype" => "CPV",
                "image_url" => "https=>//cdn.example.com/images/banner1.png",
                "htmltag" => "<iframe src='https://example.com'></iframe>",
                "from_hour" => "8",
                "to_hour" => "20",
                "hs_os" => "iOS,Desktop",
                "operator" => "Wi-Fi",
                "device_make" => "Apple,Samsung",
                "country" => "USA",
                "city" => "New York",
                "lat" => "40.7128",
                "lng" => "-74.0060",
                "app_name" => "Example App",
                "user_list_id" => "1",
                "adplay_logo" => 0,
                "vast_video_duration" => 30,
                "logo_placement" => 0,
                "hs_model" => "iPhone,Galaxy",
                "is_rewarded_inventory" => 1,
                "pixel_tag" => "<img src='https://example.com/pixel'/>",
                "dmp_campaign_audience" => 1,
                "platform" => "Web",
                "open_publisher" => 0,
                "audience_targeting" => 1,
                "native_title" => "Exciting Offers",
                "native_type" => "carousel",
                "native_data_value" => "50% OFF",
                "native_data_cta" => "Shop Now",
                "native_data_rating" => "4.5",
                "native_data_price" => "100 USD",
                "native_img_icon" => "https=>//cdn.example.com/icons/icon1.png"
            ],
            [
                "campaignname" => "Holiday_Sale_May",
                "advertiser" => "HolidayAdTech",
                "code" => "132890B56CD12XYZ8",
                "appid" => "20240510120000",
                "tld" => "https=>//holiday.com/",
                "portalname" => "",
                "creative_type" => "1",
                "creative_id" => 203948,
                "day_capping" => 5,
                "dimension" => "300x250",
                "attribute" => "display",
                "url" => "https=>//holiday.com/",
                "billing_id" => "123123123",
                "price" => 0.15,
                "bidtype" => "CPM",
                "image_url" => "https=>//holiday.com/images/holiday-banner.png",
                "htmltag" => "",
                "from_hour" => "6",
                "to_hour" => "18",
                "hs_os" => "Android,Desktop",
                "operator" => "Wi-Fi,GrameenPhone",
                "device_make" => "Samsung",
                "country" => "CAN",
                "city" => "Toronto",
                "lat" => "43.651070",
                "lng" => "-79.347015",
                "app_name" => "Holiday App",
                "user_list_id" => "2",
                "adplay_logo" => 1,
                "vast_video_duration" => null,
                "logo_placement" => 1,
                "hs_model" => null,
                "is_rewarded_inventory" => 0,
                "pixel_tag" => null,
                "dmp_campaign_audience" => 0,
                "platform" => "Mobile",
                "open_publisher" => 1,
                "audience_targeting" => 1,
                "native_title" => null,
                "native_type" => null,
                "native_data_value" => null,
                "native_data_cta" => null,
                "native_data_rating" => null,
                "native_data_price" => null,
                "native_img_icon" => null
            ]
        ];
    }
}
